#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("HaierAppTest.Resource", IsApplication=true)]

namespace HaierAppTest
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ZXing.Mobile.Resource.Id.contentFrame = global::HaierAppTest.Resource.Id.contentFrame;
			global::ZXing.Mobile.Resource.Layout.zxingscanneractivitylayout = global::HaierAppTest.Resource.Layout.zxingscanneractivitylayout;
			global::ZXing.Mobile.Resource.Layout.zxingscannerfragmentlayout = global::HaierAppTest.Resource.Layout.zxingscannerfragmentlayout;
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int in_from_bottom = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int out_from_bottom = 2130968577;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int haieracg = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int monoandroidsplash = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070002
			public const int btnBarcode = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int btnFlashBarcode = 2131165187;
			
			// aapt resource value: 0x7f07000e
			public const int btn_exit = 2131165198;
			
			// aapt resource value: 0x7f07000d
			public const int btn_login = 2131165197;
			
			// aapt resource value: 0x7f070006
			public const int btnback = 2131165190;
			
			// aapt resource value: 0x7f070005
			public const int btnsave = 2131165189;
			
			// aapt resource value: 0x7f070004
			public const int btntempsave = 2131165188;
			
			// aapt resource value: 0x7f070013
			public const int buttonZxingFlash = 2131165203;
			
			// aapt resource value: 0x7f070014
			public const int contentFrame = 2131165204;
			
			// aapt resource value: 0x7f070008
			public const int form_title = 2131165192;
			
			// aapt resource value: 0x7f070001
			public const int layout_login_name = 2131165185;
			
			// aapt resource value: 0x7f07000f
			public const int linearLayout1 = 2131165199;
			
			// aapt resource value: 0x7f070011
			public const int linearLayout2 = 2131165201;
			
			// aapt resource value: 0x7f070007
			public const int listViewBarCode = 2131165191;
			
			// aapt resource value: 0x7f07000b
			public const int login_pass_edit = 2131165195;
			
			// aapt resource value: 0x7f07000a
			public const int login_pwd_layout = 2131165194;
			
			// aapt resource value: 0x7f070000
			public const int textView1 = 2131165184;
			
			// aapt resource value: 0x7f070010
			public const int textView2 = 2131165200;
			
			// aapt resource value: 0x7f070012
			public const int textView3 = 2131165202;
			
			// aapt resource value: 0x7f070009
			public const int txt_login_name = 2131165193;
			
			// aapt resource value: 0x7f07000c
			public const int txt_login_pwd = 2131165196;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ApplicationMaster = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ZxingOverlay = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int zxingscanneractivitylayout = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int zxingscannerfragmentlayout = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int DBNAME = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Mono_Android_Theme_Splash = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
